### ISSUE TITLE
[Feedback] Steps to bootstrap the DB?

### ISSUE THREAD

**Issue by calebdinsmore** [MethSarcus/visualeague#247]
Hey, love the app! Interested in contributing, but I'm not sure how best to set up the MongoDB side of things. Is there a separate repo for db migrations, or am I just missing something here?

Thanks!

**Comment by MethSarcus** [comment]
I'll make a contributor role for the mongo database and add instructions on how to connect it in the ReadMe

**Comment by MethSarcus** [comment]
Added a guest user role and added details for creating the local env file the credentials go in, if that doesn't work let me know, I look forward to any contributions you might have :)
