### ISSUE TITLE
As a user, I would like to go from the screen with my league specific infromation back to the home screen which displays all my leagues

### ISSUE THREAD

**Issue by mue8010** [MethSarcus/visualeague#253]
Given that I have the screen with my league specific details, when I use that screen, then I would want a feature that allows me to go back to that screen so that I can browse my leagues without having to refresh the browser.

**Comment by MethSarcus** [comment]
Pressing the search icon in the navbar should bring up that same modal to select leagues from without leaving the page, let me know if that works for you

**Comment by mue8010** [comment]
Huh, that does - it's an interesting approach and probably more dynamc than what I was expecting. From a UX perspective was a bit confused where to click but this approach provides more flexibity for if there are multiple users or is part of many leagues. I had originally thought there would be a selection in the form of a league select dropdown.
