### ISSUE TITLE
Week 15 (2023) matchups show 0.0 points for all teams

### ISSUE THREAD

**Issue by haGibear** [MethSarcus/visualeague#318]
**Describe the bug**
Player scores and matchup scores all show 0.0 for week 15 (2023 season).

**League ID**
918076606789300224 (and every other league I have tested)

**Comment by MethSarcus** [comment]
**Bug fixed**
Cause: I drank myself to sleep after losing my playoff match and did not update the stats as a side note hate fantasy football

**Comment by haGibear** [comment]
I feel for you, man. I think I'll never get over losing last year's final by 2 points against a guy who started Stidham as his SF, would've been back to back dynasty titles.
