### ISSUE TITLE
One league isn't working

### ISSUE THREAD

**Issue by curzlite** [MethSarcus/visualeague#372]
One of my leagues, but the other isn't loading. I'm getting an error message that says, "Application error: a client-side exception has occurred (see the browser console for more information)."

**Steps To Reproduce**
1. 

**League ID**
1048227353018658816

**Additional context**

**Comment by MethSarcus** [comment]
@curzlite Has the league drafted yet? Ill make it fail more gracefully but there needs to be at least a week worth of stats to work, unless theres some functionality you want to access that doesnt require that?

**Comment by curzlite** [comment]
The draft hasn’t started yet, but I’m selecting the 2023 season. Shouldn’t the 2023 data be able to upload without the 2024 draft?Thanks for the response. Sent from my iPhoneOn Jul 12, 2024, at 1:26 PM, Seth Marcus ***@***.***> wrote:﻿
@curzlite Has the league drafted yet? Ill make it fail more gracefully but there needs to be at least a week worth of stats to work, unless theres some functionality you want to access that doesnt require that?

**Comment by MethSarcus** [comment]
Just about to merge a fix it was because a user left the league, thanks for reporting! As a side note the leagueID you posted was for a 2024 league the league ID for the 2023 league is 929612530937364480

**Comment by curzlite** [comment]
Thank you, appreciate it!Will the site also work for 2024 league?Thanks Sent from my iPhoneOn Sep 4, 2024, at 3:15 PM, Seth Marcus ***@***.***> wrote:﻿
Just about to merge a fix it was because a user left the league, thanks for reporting! As a side note the leagueID you posted was for a 2024 league the league ID for the 2023 league is 929612530937364480

**Comment by MethSarcus** [comment]
It will once stats are logged after week 1
