### ISSUE TITLE
Add a shareable url for individual leagues

### ISSUE THREAD

**Issue by calebpriester** [MethSarcus/visualeague#8]
**Is your feature request related to a problem? Please describe.**
Right now, in order to share MFN with league-mates or people who are interested, I have to point them to the site and provide a league id. This is tedious to have to do.

**Describe the solution you'd like**
I would like a shareable url that includes info like league id and year so that I can bookmark leagues I frequently look at but also to make sharing the dashboard for my league simpler.

**Comment by MethSarcus** [comment]
Closing as the new site does this by default
